import type { Config } from 'tailwindcss';

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      spacing: {
        '4.5': '1.125rem', // 18px
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
        headline: ['Manrope', 'Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        body: ['Manrope', 'Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      colors: {
        heal: {
          blue: 'var(--color-primary)',
          blueDark: 'var(--color-primary-dark)',
          blueLight: 'var(--color-primary-light)',
          teal: '#10B981',
          tealDark: '#059669',
          tealSoft: '#D1FAE5',
          ink: '#1C1C1E',
          inkSecondary: '#3A3A3C',
          muted: '#6B6B70',
          mutedLight: '#A0A0A5',
          line: '#E5E5EA',
          lineStrong: '#C7C7CC',
          canvas: '#F2F2F7',
          surface: '#FFFFFF',
          surfaceHover: '#EFEFF4',
          softBlue: 'var(--color-soft-blue)',
          success: '#10B981',
          successSoft: '#D1FAE5',
          danger: '#EF4444',
          dangerSoft: '#FEE2E2',
          warning: '#F59E0B',
          warningSoft: '#FEF3C7',
        },
        surface: 'var(--surface)',
        'surface-dim': 'var(--surface-dim)',
        'surface-bright': 'var(--surface-bright)',
        'surface-container-lowest': 'var(--surface-container-lowest)',
        'surface-container-low': 'var(--surface-container-low)',
        'surface-container': 'var(--surface-container)',
        'surface-container-high': 'var(--surface-container-high)',
        'surface-container-highest': 'var(--surface-container-highest)',
        'surface-variant': 'var(--surface-variant)',
        background: 'var(--background)',
        primary: 'var(--primary)',
        'primary-container': 'var(--primary-container)',
        'on-primary': 'var(--on-primary)',
        'on-primary-container': 'var(--on-primary-container)',
        secondary: 'var(--secondary)',
        'secondary-container': 'var(--secondary-container)',
        tertiary: 'var(--tertiary)',
        'tertiary-container': 'var(--tertiary-container)',
        error: 'var(--error)',
        'error-container': 'var(--error-container)',
        'on-error': 'var(--on-error)',
        'on-error-container': 'var(--on-error-container)',
        'on-surface': 'var(--on-surface)',
        'on-surface-variant': 'var(--on-surface-variant)',
        'on-background': 'var(--on-background)',
        outline: 'var(--outline)',
        'outline-variant': 'var(--outline-variant)',
      },
      borderRadius: {
        card: 'var(--radius-card)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
      },
      boxShadow: {
        xs: 'var(--shadow-xs)',
        soft: 'var(--shadow-soft)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        blue: 'var(--shadow-blue)',
        ambient: 'var(--shadow-ambient)',
      },
      animation: {
        'fade-in': 'heal-fade-in 250ms ease-out',
        'slide-up': 'heal-slide-up 250ms ease-out',
        'slide-down': 'heal-slide-down 250ms ease-out',
        'scale-in': 'heal-scale-in 250ms ease-out',
        'spin-slow': 'heal-spin 1.5s linear infinite',
        'pulse-soft': 'heal-pulse 2s ease-in-out infinite',
      },
      keyframes: {
        'heal-fade-in': {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        'heal-slide-up': {
          from: { opacity: '0', transform: 'translateY(12px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'heal-slide-down': {
          from: { opacity: '0', transform: 'translateY(-8px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'heal-scale-in': {
          from: { opacity: '0', transform: 'scale(0.95)' },
          to: { opacity: '1', transform: 'scale(1)' },
        },
        'heal-spin': {
          to: { transform: 'rotate(360deg)' },
        },
        'heal-pulse': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.5' },
        },
      },
    },
  },
  plugins: [],
} satisfies Config;
